"""
Tutorial: Simulating User Conversations
Demonstrates how to use Galtea's Conversation Simulator to test your AI with a synthetic user.
"""

from datetime import datetime

import galtea
from galtea import Galtea

run_identifier = datetime.now().strftime("%Y%m%d%H%M%S")

galtea_client = Galtea(api_key="YOUR_API_KEY")

# Create a product for this demo
client = getattr(galtea_client, "_Galtea__client", None)
if client is None:
    raise ValueError("Could not access Galtea client for direct API call")
response = client.post(
    "products",
    json={
        "name": "Simulation Demo " + run_identifier,
        "description": "Demo product for conversation simulation tutorial",
        "capabilities": "Demo capabilities",
        "inabilities": "Demo inabilities",
        "securityBoundaries": "Demo security boundaries",
    },
)
product_id = response.json()["id"]


# @start implement_agent
@galtea.trace(name="main_agent")
def my_agent(user_message: str) -> str:
    """Your main agent logic"""
    return "useful_response"


class MyGalteaAgent(galtea.Agent):
    @galtea.trace(name="main")
    def call(self, input_data: galtea.AgentInput) -> galtea.AgentResponse:
        # Access the latest user message
        user_message = input_data.last_user_message_str()

        # Generate a response using your own logic/model
        response = my_agent(user_message)

        # Return a structured response (optionally with metadata and retrieval context)
        return galtea.AgentResponse(
            content=response,
            retrieval_context=None,  # Optional: context retrieved by the agent (e.g., for RAG)
            metadata=None,  # Optional: additional metadata
        )


# @end implement_agent


# Call the product and version you want to evaluate
product = galtea_client.products.get(product_id=product_id)
if product is None:
    raise ValueError("product is None")
version_name = "v1.0-" + run_identifier
version = galtea_client.versions.create(
    name=version_name,
    product_id=product.id,
    description="Version created from the tutorial",
    model_id="ru45tcu3bnqibuswhla4omyt",
)
if version is None:
    raise ValueError("version is None")

test_name = f"Multi-turn Conversation Test-{run_identifier}"

# @start create_test_and_sessions
# Create a test suite using the scenarios options
# This can be done via the Dashboard or programmatically as shown here
test = galtea_client.tests.create(
    product_id=product.id,
    name=test_name,
    type="SCENARIOS",
    # This time we provide a path to a CSV file with scenarios, but you can also be generated by Galtea if you do not provide a CSV file
    test_file_path="path/to/scenarios_test.csv",
)

# Get your test scenarios
# If Galtea is generating the test for you, it might take a few moments to be ready
test_cases = galtea_client.test_cases.list(test_id=test.id)
# @end create_test_and_sessions

if test_cases is None or len(test_cases) == 0:
    raise ValueError("No test cases found")


# @start run_simulator
# Create your agent instance
agent = MyGalteaAgent()

# Run simulations
for test_case in test_cases:
    session = galtea_client.sessions.create(
        version_id=version.id, test_case_id=test_case.id
    )

    result = galtea_client.simulator.simulate(
        session_id=session.id, agent=agent, max_turns=10, log_inference_results=True
    )

    # Analyze results
    print(f"Scenario: {test_case.scenario}")
    print(f"Completed {result.total_turns} turns")
    print(f"Success: {result.finished}")
    if result.stopping_reason:
        print(f"Ended because: {result.stopping_reason}")
    # @end run_simulator

    # @start evaluate_session
    # After each simulation, you can create an evaluation
    evaluations = galtea_client.evaluations.create(
        session_id=session.id,
        metrics=[{"name": "Role Adherence"}],  # Replace with your metrics
    )
    for evaluation in evaluations:
        print(f"Evaluation created: {evaluation.id}")
# @end evaluate_session


# @start rag_agent
class MyRAGAgent(galtea.Agent):
    def __init__(self, vector_store, llm):
        self.vector_store = vector_store
        self.llm = llm

    def call(self, input_data: galtea.AgentInput) -> galtea.AgentResponse:
        user_message = input_data.last_user_message_str()

        # Your RAG logic to retrieve context and generate a response
        retrieved_docs = self.vector_store.search(user_message)
        response_content = self.llm.generate(
            prompt=user_message, context=retrieved_docs
        )

        return galtea.AgentResponse(
            content=response_content,
            retrieval_context=retrieved_docs,
            metadata={"docs_retrieved": len(retrieved_docs)},
        )


# @end rag_agent


# === Cleanup ===
galtea_client.products.delete(product_id=product_id)
